#..............................................
# ........Project : Software Assessment...............
#..........Name : Danilo Cunha Marino...............
#...............08/05/2025....................

#...Fuction which start average calculation....
def calculate_average(scores):
    return sum(scores) / len(scores)
#...Fuction which end average calculation....

#...Function to give us the grade...
def assign_grade(average):
    if average >= 80:
        return 'A'
    elif average >= 70:
        return 'B'
    elif average >= 60:
        return 'C'
    elif average >= 50:
        return 'D'
    else:
        return 'F'